# Generated by CMake, DO NOT EDIT
# Custom rules for ALL_BUILD
.SUFFIXES: 
all: \
	/Users/ssmilkshake/Documents/MUSIC-8903-2016-Assignment1/bld/CMakeFiles/ALL_BUILD


/Users/ssmilkshake/Documents/MUSIC-8903-2016-Assignment1/bld/CMakeFiles/ALL_BUILD: 
	echo ""
	echo Build\ all\ projects
