# Generated by CMake, DO NOT EDIT
# Custom rules for ZERO_CHECK
.SUFFIXES: 
all: \
	/Users/ssmilkshake/Documents/MUSIC-8903-2016-Assignment1/bld/CMakeFiles/ZERO_CHECK


/Users/ssmilkshake/Documents/MUSIC-8903-2016-Assignment1/bld/CMakeFiles/ZERO_CHECK: 
	echo ""
	make -f /Users/ssmilkshake/Documents/MUSIC-8903-2016-Assignment1/bld/CMakeScripts/ReRunCMake.make
